spring.application.name=aggregator
server.port=0

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.admin.fail-fast=false
spring.kafka.consumer.group-id=aggregator-user-actions
spring.kafka.consumer.auto-offset-reset=earliest

ewm.kafka.topic.user-actions=stats.user-actions.v1
ewm.kafka.topic.events-similarity=stats.events-similarity.v1
