spring.application.name=aggregator
server.port=0

eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:29092}
spring.kafka.admin.fail-fast=false
spring.kafka.admin.properties[request.timeout.ms]=3000
spring.kafka.admin.properties[default.api.timeout.ms]=3000
spring.kafka.consumer.group-id=aggregator-user-actions
spring.kafka.consumer.auto-offset-reset=earliest

ewm.kafka.topic.user-actions=stats.user-actions.v1
ewm.kafka.topic.events-similarity=stats.events-similarity.v1
