server.port=0
grpc.server.port=19091
eureka.instance.metadata-map.grpcPort=${grpc.server.port}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5437/analyzer
spring.datasource.username=analyzeruser
spring.datasource.password=analyzerpass
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id-actions=analyzer-user-actions-group
spring.kafka.consumer.group-id-similarity=analyzer-similarity-group
