server.port=0
grpc.server.port=9090
eureka.instance.metadata-map.grpcPort=${grpc.server.port}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
