spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ewm
    username: ewmuser
    password: ewmpass
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
