spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/ewm
spring.datasource.username=ewmuser
spring.datasource.password=ewmpass

stats-server.service-id=stats-server

logging.level.root=DEBUG