server.port=0
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/users
spring.datasource.username=usersuser
spring.datasource.password=userspass
spring.sql.init.mode=always
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
