spring.application.name=config-server
server.port=8888

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config,file:../../core/event-service/src/main/resources,file:../../core/user-service/src/main/resources,file:../../core/request-service/src/main/resources,file:../../core/compilation-service/src/main/resources,file:../../stat/stat-server/src/main/resources,file:../gateway-server/src/main/resources

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
