CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000),
    category_id BIGINT,
    created_on TIMESTAMP NOT NULL,
    description VARCHAR(7000),
    event_date TIMESTAMP NOT NULL,
    initiator BIGINT NOT NULL,
    lat FLOAT,
    lon FLOAT,
    paid BOOLEAN,
    participant_limit INTEGER,
    published_on TIMESTAMP,
    request_moderation BOOLEAN,
    state VARCHAR(20),
    title VARCHAR(120)
);
